export default {
    FONT_SIZE_SMALL: 12,
    FONT_SIZE_MEDIUM: 14,
    FONT_SIZE_LARGE: 16,
    PRIMARY_COLOR: 'rgb(0,0,0)',
    SECONDARY_COLOR: 'rgb(238, 167, 2)',
    FONT_WEIGHT_LIGHT: 200,
    FONT_WEIGHT_MEDIUM: 600,
    FONT_WEIGHT_HEAVY: 800,
    PRIMARY_BACKGROUND_COLOR: '#841584',
    SECONDARY_BACKGROUND_COLOR: '#ce33ce'
};