export const GENERATE_OTP_FAIL = 'GENERATE_OTP_FAIL';
export const GENERATE_OTP_SUCCESSS = 'GENERATE_OTP_SUCCESSS';
export const VALIDATE_OTP_SUCCESS = 'VALIDATE_OTP_SUCCESS';
export const VALIDATE_OTP_FAIL = 'VALIDATE_OTP_FAIL';
export const LOADING = 'LOADING';
export const LOGOUT_USER = 'LOGOUT_USER';